// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFZy7PxWO69iaT5GEdBf91rK1BaA8S3FQ',
    appId: '1:592182688789:web:4597bbc14253b2b106e21c',
    messagingSenderId: '592182688789',
    projectId: 'bgc-tp3',
    authDomain: 'bgc-tp3.firebaseapp.com',
    storageBucket: 'bgc-tp3.firebasestorage.app',
    measurementId: 'G-65LSKB5PXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAxd_mYbGEEe3QhnzwoZTMDmGkwOyRgPA',
    appId: '1:592182688789:android:ddaedfef81d8162c06e21c',
    messagingSenderId: '592182688789',
    projectId: 'bgc-tp3',
    storageBucket: 'bgc-tp3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABvj5uSXeLPKm-a3CYqrvK4A_7dm78uNk',
    appId: '1:592182688789:ios:7025465687c5f84c06e21c',
    messagingSenderId: '592182688789',
    projectId: 'bgc-tp3',
    storageBucket: 'bgc-tp3.firebasestorage.app',
    iosBundleId: 'com.example.bgcV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABvj5uSXeLPKm-a3CYqrvK4A_7dm78uNk',
    appId: '1:592182688789:ios:7025465687c5f84c06e21c',
    messagingSenderId: '592182688789',
    projectId: 'bgc-tp3',
    storageBucket: 'bgc-tp3.firebasestorage.app',
    iosBundleId: 'com.example.bgcV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFZy7PxWO69iaT5GEdBf91rK1BaA8S3FQ',
    appId: '1:592182688789:web:bead89553122c94e06e21c',
    messagingSenderId: '592182688789',
    projectId: 'bgc-tp3',
    authDomain: 'bgc-tp3.firebaseapp.com',
    storageBucket: 'bgc-tp3.firebasestorage.app',
    measurementId: 'G-FES3SEGQW3',
  );
}
